### ISSUE TITLE
Eidos "return" not working in R

### ISSUE THREAD

**Issue by rhiannon-schembri** [rdinnager/slimr#63]
Hi Russell,

I'm trying to use slimr to make a bunch of slim scripts from different parameter values in a template. One of the blocks in my slim script is taken from slim recipe 14.15 II - the mutation callback. R doesn't seem to like the "return" functions in this block. It throws an error ("unexpected symbol in..") for both "return" lines. 
![image](https://user-images.githubusercontent.com/32833669/226253079-72c8ee6e-8f15-403e-93a1-91190eb77f4e.png)
![image](https://user-images.githubusercontent.com/32833669/226253258-1bee1db0-1a5e-460c-b99d-e56d3ddd58cb.png)

"mutation" also isn't listed in the slim_block help file as a valid callback, so not sure if this is causing the problem.

Thanks for your help,
Rhiannon

**Comment by rdinnager** [comment]
Hi @rhiannon-schembri ,

Apologies for not getting back to you on this. I actually never received a notification of this issue for some reason, and I haven't been watching the repo closely because `slimr` has been on my back-burner for awhile. Anyway, I've now restarted development. I don't know if you are still interested in this but for the record, there were two issues here. The first is, as you noted, `mutation()` was not in the `slimr` callbacks. I number of callbacks got added to SLiM since I started writing `slimr`, including `mutation()`, which 
I hadn't had a chance to add into `slimr` until recently. `slimr` now has `mutation()` callbacks so that part at least should work now. 

The other issue is that in `slimr`, you must use `return(T);` instead of `return T;`. This is to make it compatible with the R interpreter. This gets correctly replaced when the script is converted to SLiM. I realise this particular quirk is not well documented as of yet. I am working on a table that I will add to the readme and the `slimr` documentation that lists small differences like this between `slimr` and SLiM that should be kept in mind.

Just for future reference, when posting issues it is good practice to post a minimal reproducible example to help me test whether any fix I might make actually solves the problem. At the very least, please copy and paste the code and error message into the issue rather than using a screenshot, which just helps me quickly copy and paste code or error message for searching. If you are still interested in getting this model running in `slimr`, please test it with the latest version by reinstalling `slimr` from github, and let me know whether the issue persists.

Again, apologies for missing this issue, but thank you for your interest. I am now updating `slimr` extensively and soon will submit it to a journal. `slimr` is now compatible with SLiM 4.0 and greater, in case that is of interest.
